###GET admin
GET http://localhost:3000/admin
###GET admin com id
GET http://localhost:3000/admin/155
Content-Type: application/json
{
    "nome": "gabriel",
    "senha": "452325"
}
###GET usuarios
GET http://localhost:3000/usuario
###GET usaurios com id
GET http://localhost:3000/usuario/155
Content-Type: application/json
{
    "nome": "gabriel",
    "senha": "452325"
}

### Acessando via Path
PATCH http://localhost:3000/admin/155

### Acessando via Put
PUT http://localhost:3000/admin/155

### Acessando via DELETE
DELETE http://localhost:3000/admin/155